### ISSUE TITLE
XSParql parsing fails if SPARQL query contains inner curly braces in UNION or OPTIONAL

### ISSUE THREAD

**Issue by tfrancart** [semantalytics/xsparql#20]
```
declare namespace eli = "http://data.europa.eu/eli/ontology#";
<ELI xmlns:eli="http://data.europa.eu/eli/ontology#">
{
  for $LegalResource from <eli-data.ttl>
  where { 
  	$LegalResource a eli:LegalResource .
  	OPTIONAL { $LegalResource eli:in_force ?in_force . }
  }
  return 
  <LegalResource eli:URI="{$LegalResource}" />
}
</ELI>
```

Produces

```
line 4:2 mismatched input 'for' expecting LCURLY
line 6:3 mismatched input '$LegalResource' expecting LCURLY
line 7:14 mismatched input '$LegalResource' expecting LCURLY
line 9:2 mismatched input 'return' expecting ENDELM
line 11:16 no viable alternative at input ' '
Parse error: java.lang.Exception: Errors for Parser. Translation aborted.
java.lang.Exception: Errors for Parser. Translation aborted.
	at org.sourceforge.xsparql.rewriter.XSPARQLProcessor.process(XSPARQLProcessor.java:233)
	at org.sourceforge.xsparql.Main.rewriteQuery(Main.java:189)
	at org.sourceforge.xsparql.Main.main(Main.java:103)
```

This happens as soon as the "where" clause contains an inner pair of curly braces in an OPTIONAL or a UNION.

**Comment by tfrancart** [comment]
Disregard this issue. The cause is that the variable should start with a '$' and not a '?'
